$kind: http-request
method: PUT
url: '{{baseUrl}}/api/v1/tasks/{{taskId}}'
order: 4000
auth:
  type: bearer
  credentials:
    - key: token
      value: '{{token}}'
headers:
  - key: Content-Type
    value: application/json
body:
  type: json
  content: |-
    {
      "title": "Updated Task",
      "description": "Updated",
      "status": "in_progress"
    }
